### ISSUE TITLE
[oracle-node] Implement a mechanism to save values from sources in the new nodes

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-oracles-monorepo#213]
Our old oracle-node (all files with the `Old.ts` ending) was saving much more data in the redstone api. Not only the signed data packages, but also some information about values from each source. We would like to add similar functionality to the new nodes for being able to finally get rid of the old nodes.

Maybe we would need to extend the cache service with this functionality. But maybe you can propose a better solution.

Within this issue we would like to discuss the best possible solution for this.

## Potential steps
- Understand the code of the `*Old.ts` files in the oracle node
- Understand the code of the https://github.com/redstone-finance/redstone-api as it contains all the logic for efficient saving and querying this type of data
- Understand the basics of the redstone web app (https://github.com/redstone-finance/redstone-app)
- Prepare a plan, how you would implement this change, let's discuss it with Alex and Cezary
- Implement the selected solution 🚀

**Comment by Lukasz2891** [comment]
1) implement prices broadcasting to a newly created cache-service/prices endpoint
* similar like broadPrices in NodeRunnerOld, but the data packages to be signed are limited to: ```{source: Object, symbol, timestamp, version, value, provider }``` (so the ```permawebTx``` and ```id``` are removed, ```liteEvmSignature``` is changed to ```signature``` }
2) implement cache-service/prices endpoint to take the data prepared, using ```POST``` http method 
3) verify the signature of the data sent [optional]
4) save the data to a storage like the data packages are 

Questions:
* Do we need the old version remained as an option in the config or should we clean-up the code permanently?
