### ISSUE TITLE
[oracle-node] Skip broadcasting of "big" data package if it doesn't contain at least X data points

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-oracles-monorepo#294]

**Comment by cehali** [comment]
Add config params MIN_PERCENTAGE_OF_VALID_DATA_FEEDS_VALUES_TO_CREATE_BIG_PACKAGE or MAX_NUMBER_OF_MISSING_DATA_FEEDS_TO_CREATE_BIG_PACKAGE
