### ISSUE TITLE
analyze `npm audit` output and fix easy fixable

### ISSUE THREAD

**Issue by koonopek** [redstone-finance/redstone-oracles-monorepo#479]
Result of analyzing `yarn audit` output (I don't find any of them as risky for us):
- [ ] cookiejar >= 2.1.4
    - cache-serivce/@bundlr-network
- [ ] ua-parser-js >= 0.7.33
    - oracle-monitoring-frontend > react-json-view
- [ ] luxon >=1.28.1
    -  @redstone-finance/cache-service > @nestjs/schedule
- [ ] http-cache-semantics >=4.1.1
    -  redstone-streamr-proxy > streamr-client
- [ ] @openzeppelin/contracts-upgradeable >= 4.8.2
    - redstone-on-chain-relayer
    - @redstone-finance/evm-connector
- [ ] sqlite3 >=5.1.5
    - redstone-streamr-proxy > streamr-client
- [ ] node-fetch >=2.6.7
    - redstone-oracle-node > @balancer-labs/sdk
- [ ] @openzeppelin/contracts  >=4.7.3 
    -  @redstone-finance/evm-connector > @chainlink/contracts 
    - redstone-on-chain-relayer > @redstone-finance/evm-connector 
- [ ] undici >=5.19.1
    - warp-contracts :)
- [ ] update yahoo-finance
    
However this list may not be full, look on security tab on this repository you will see 44 warnings there, not all of them are reported by `yarn audit` I propose adding dependant bot to repository witch will update deps, by creating pull requests:
How to: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates

**Comment by koonopek** [comment]
@hatskier I'm not sure if we want to update so many dependecies in one batch, there is always risk that something will break and it will be hard to debug (I would leave it dependantbot if we are willing to enable it).

**Comment by koonopek** [comment]
I tried doing it "by hand", however it is very hard you have to travel all dependency tree.

**Comment by hatskier** [comment]
Okay, let's use dependabot. We already have it actually in monorepo, do you (@koonopek) have access to it?

**Comment by koonopek** [comment]
Yes, but only in readonly mode.
Now it is configured to send notifications about potential fixes, I would suggest configuring it to create pull request with fixs in yarn.lock - here is the instruction: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates (i can do it if we agree on that)

**Comment by hatskier** [comment]
Yes, let's do it please!
