### ISSUE TITLE
Create a magic blockchain provider tailored for RedStone oracle needs

### ISSUE THREAD

**Issue by hatskier** [redstone-finance/redstone-oracles-monorepo#511]
We can keep the implementation in redstone-sdk or in a new package, because it can be reused in oracle-node and on-chain-relayers

The most important features of the provider:
- Fallbacks (with several RPC urls)
- [Magic, but the most important] batching rpc calls to pay less for commercial RPC providers. We need to research how to create those batches (e.g. having a timer for ~200 ms or using js ticks [like here](https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/json-rpc-batch-provider.ts#L9))
  - Option 1. MultiCall contracts (have limits in terms of number of calls)
  - Option 2. https://docs.ethers.org/v5/api/providers/other/#JsonRpcBatchProvider or something with a similar mechanism. But we need to be sure that our rpc urls support batch requests
- Aggregating between several RPC urls (comparing values between and expecting the same or similar answer)

**Comment by hatskier** [comment]
After implementing this magic provider we can refactor the old fallback mechanism for Avalanche Evm Fetcher

**Comment by koonopek** [comment]
https://www.npmjs.com/package/ethers-multicall-provider

**Comment by koonopek** [comment]
Every call static or not is executed by Provider::call. How to distinguish writes from reads? It is not possible in the provider the only differnece is that writes doesnt return results, however doing multiple writes is still kind of okey, but awaiting for the results using only one node.

**Comment by koonopek** [comment]
On balance after reading the fallback provider from ethers implementation, our implementation should look like this:
1. Don't use quorum. (We don't want to sacrifice reliability for decentralization (use multiple nodes if they work if not use even the single one) => if node doesn't response count it as the same result)
2. Confirmation about tx including from one node is enough (but broadcast to many) 
3. Use the lowest value of getBlockNumber from all nodes (fastest solution, we don't have to wait for the sync of nodes, the info can be a little bit stale but it can always be) 
4. Estimate gas using only one provider
5. Strictly compare provider.call results if (read) if write nothing to compare

**Comment by hatskier** [comment]
1. IMHO decentralization can also be valuable (esp. in case of oracle fetchers). WDYT about using quorum but with a smaller percentage (e.g. 30% instead of 50%)?
2. I agree
3. Agree, the only case to consider is when one node is significantly non-synced and has too old block number
4. Agree, but which one? :)
5. Agree
6. Not sure I if understand this
7. Agree

**Comment by koonopek** [comment]
I think that JsonRpcProvider should not be implemented because of #631
