### ISSUE TITLE
Fuel connector review

### ISSUE THREAD

**Issue by jakub-wojciechowski** [redstone-finance/redstone-oracles-monorepo#619]
SHOWROOM:
1. Let's please remove other chains from the FUEL showroom, we may also change domain (let's not use vercel): https://redstone-showroom-git-fuel-redstone-finance.vercel.app/
3. Writing transactions on showroom doesn't work (the page is cleared without any feedback)

Contracts README: 
4. I don't get this part from README: 
"When the skip_setting_owner flag is set to 0, the contract becomes owned by the function invoker. To avoid that, the skip_setting_owner should be set to 0."
5. "That initializer can be invoked only by the owner or by anyone when no owner was previously set." -> but we set an owner in the initializer, can we invoke it multiple times?
6. It'll be great to explain what is XXX in the script and where the output file goes (package-generator): 
"You can use: [Makefile](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/359-implement-sway-adapter/packages/protocol/scripts/payload-generator/Makefile) by invoking make DATA_NAME=xxx prepare_data or directly from the [payload-generator](https://github.com/redstone-finance/redstone-oracles-monorepo/blob/359-implement-sway-adapter/packages/protocol/scripts/payload-generator) environment directory."

MAIN README:
It'll be great to add a small intro with a context (What are Oracles, What is Redstone, what is the Fuel Connector -> 1,2 sentence for each is enough). Also in the footer let's write sth about the Fuel Grant programme (Proudly supported by Fuel Grants programme) at the top level. 
We may mention what is included in the fuel-connector packages: 
1) src -> front-end connector code
2) sway -> smart contract libraries and examples
3) tests

SWAY README:
 
1. Let's explain what is a program (maybe let's call it "running data-processing script", and explain that is used to debug the data-processing logic). Let's explain what happens in the program (step-by-step) and what users sees in the results.

2. Changing the URL and running cash service are advanced tasks, let's focus on generating payload and put the possible extensions as optional comments (messing with URL could lead to connecting to data service without proper tokens)
3. Let's mention that it's necessary to run fuel-core (chain)

5. We may mention that there is the need to copy-paste address only if we change sth in the code

**Comment by Lukasz2891** [comment]
A) The address of the showroom is now: https://fuel-showroom.redstone.finance/

B) Initializer is explained and the wrong constant 0/1 is also fixed.

C) [almost all] Changes in readmes are done, especially a new intro-README file is added to the whole fuel-connector package: https://github.com/redstone-finance/redstone-oracles-monorepo/tree/359-implement-sway-adapter/packages/fuel-connector#readme

D) I'm going to find the reason of the reloaded page during writing the transaction.

E)

F) The structure of putting CONTRACT_ID to Forc.ml and generally configuring the contracts/scripts has changed in sway `0.36.0`, so Idk if we want to automatize it now.
